# CLI Tools (Formulae)
brew "awscli"
brew "bat"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git-delta"
brew "go"
brew "k6"
brew "kubernetes-cli"
brew "lazygit"
brew "nvm"
brew "pdfcpu"
brew "python"
brew "scrcpy"
brew "tree"
brew "zsh-syntax-highlighting"

# GUI Apps and Binaries (Casks)
cask "android-platform-tools"
cask "discord"
cask "docker-desktop"
cask "font-meslo-for-powerlevel10k"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "kiro-cli" # previously amazon-q
cask "notion"
cask "obs"
cask "postman"
cask "raycast"
cask "tableplus"
cask "visual-studio-code"

# VSCode Extensions
vscode "albert.tabout"
vscode "antfu.iconify"
vscode "bierner.markdown-mermaid"
vscode "bradlc.vscode-tailwindcss"
vscode "esbenp.prettier-vscode"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "inferrinizzard.prettier-sql-vscode"
vscode "liuchao.go-struct-tag"
vscode "mechatroner.rainbow-csv"
vscode "pkief.material-icon-theme"
vscode "usernamehw.errorlens"
vscode "vue.volar"